name: GitHub Action

on: 
  push:
    branches: hmg
jobs:
  conditional_step:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD
        
        $change1 = 'src/change1.yml'
        $change2 = 'src/change2.yml'

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match $change1 -or $_ -match $change2 }
        
        echo $SourceDiff[1]

        # Set the output named "docs_changed"
        Write-Host "::set-output name=files_changed::$SourceDiff"
