name: GitHub Action

on: 
  push:
    branches: hmg
jobs:
  conditional_step:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - name: Run a sh script from a file
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: sh .github/changed-files.sh
      shell: pwsh
        
    # Run the step only with "docs_changed" equals "True"
    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.files_changed1 == 'src/change1.yml'
      run: echo 'Changes 1'
    # Run the step only with "docs_changed" equals "True"
    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.files_changed2 == 'src/change2.yml'
      run: echo 'Changes 2'
