name: GitHub Action

on: 
  push:
    branches: hmg
jobs:
  conditional_step:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match 'src/change1.yml' -or $_ -match 'src/change2.yml' }

        # Set the output named "docs_changed"
        Write-Host "::set-output name=files_changed::$SourceDiff"

    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      run: |
        echo $steps.check_file_changed.outputs.files_changed
      
    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.files_changed['src/change2.yml']
      run: echo 'Mudança no arquivo change2.yml'
