name: Update or create secrets

on:
  workflow_dispatch:
    inputs:
      secretName1:
        description: 'Secret name'
        required: true
      secretValue1:
        description: 'Secret value'
        required: true
      secretName2:
        description: 'Secret name'

      secretValue2:
        description: 'Secret value'

      secretName3:
        description: 'Secret name'
 
      secretValue3:
        description: 'Secret value'

      secretName4:
        description: 'Secret name'

      secretValue4:
        description: 'Secret value'

      secretName5:
        description: 'Secret name'

      secretValue5:
        description: 'Secret value'

jobs:
  secret:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Update or create secrets
      uses: RenanSampaioZ/GitHubActionTest2@master
      with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        token: ${{ secrets.SECRET }}
        secretName: ${{ github.event.inputs.secretName1 }}
        secretValue: ${{ github.event.inputs.secretValue1 }}
