name: GitHub Action

on: 
  push:
    branches: hmg
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: |
          git diff --name-only
