name: Secret Value

on: 
  workflow_dispatch:
    inputs:
      secret:
        description: 'Secret value'
        required: true        

jobs:
  secret-value:
    runs-on: ubuntu-latest
    steps:
      - name: Secret Value
        run: |
          if [ "$TEST" == ${{ github.event.inputs.secret }} ]
          then
            echo "Got secret"
          else 
            echo "Wrong secret value"
          fi
        env:
          TEST: ${{ secrets.TEST }}
  
