name: GitHub Action

on: 
  push:
    branches: hmg
jobs:
  conditional_step:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match 'src/change1.yml' -or $_ -match 'src/change2.yml' }

        echo $SourceDiff.'scr/change1.yml'

        # Set the output named "files_changed"
        Write-Host "::set-output name=files_changed::$SourceDiff"
        
    # Run the step only with "docs_changed" equals "True"
    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.files_changed.'src/change1.yml' == 'src/change1.yml'
      run: echo 'Changes 1'
    # Run the step only with "docs_changed" equals "True"
    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.files_changed[1] == 'src/change2.yml'
      run: echo 'Changes 2'
