name: GitHub Action

on: 
  push:
    branches: hmg
jobs:
  conditional_step:
    env:
      CHANGE1: 'src/change1.yml'
      CHANGE2: 'src/change2.yml'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match "${{ env.CHANGE1 }}" -or $_ -match "${{ env.CHANGE2 }}" }

        echo $SourceDiff["${{ env.CHANGE1 }}"]
        echo $SourceDiff["${{ env.CHANGE2 }}"]

        # Set the output named "files_changed"
        Write-Host "::set-output name=files_changed::$SourceDiff"
        
    # Run the step only with "docs_changed" equals "True"
    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.files_changed[0] == "${{ env.CHANGE1 }}"
      run: echo 'Changes 1'
    # Run the step only with "docs_changed" equals "True"
    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.files_changed[1] == "${{ env.CHANGE2 }}"
      run: echo 'Changes 2'
