name: GitHub Action

on: 
  push:
    branches: develop
jobs:
  conditional_step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2

      - name: Azure Kubernetes Service - Deployment de Web App
        run: |
          #!/bin/bash

          # Assign the filename
          filename="src/deployment.yaml"
          # Take the replace string
          read -p "Enter the replace string: " replace          
          if [[ $replace != "" ]]; then
          sed -i "s/latest/$replace/gi" $filename
          fi
          cat $filename
