name: GitHub Action

on: 
  push:
    branches: hmg
jobs:
  conditional_step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - name: Checking if Deployment and Servico-Deployment Files have changed
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD
          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiffDeployment = $diff | Where-Object { $_ -match '^src/deployment.yaml' }
          $SourceDiffServicoDeployment = $diff | Where-Object { $_ -match '^src/servico-deployment.yaml' }
          # Set the output
          echo "deployment=$SourceDiffDeployment" >> $GITHUB_OUTPUT
          echo "servicodeployment=$SourceDiffServicoDeployment" >> $GITHUB_OUTPUT
        shell: pwsh

      - name: Azure Kubernetes Service - Deployment de Web App
        run: |
          if ${{ steps.check_file_changed.outputs.deployment == 'src/deployment.yaml' }}  || ${{ steps.check_file_changed.outputs.servicodeployment == 'src/servico-deployment.yaml' }}; then
            echo "Arquivos mudaram";
          else
            echo "Arquivos não mudaram";
          fi
